version: 2

sources:
  - name: raw
    database: dagster_load  
    schema: raw
    tables:
      - name: events
      - name: okta_users
      - name: customer
      - name: customer_detail
      - name: customer_data
      - name: customer_address_data
      - name: upstream_python_asset
        meta:
          dagster:
            asset_key: ["upstream_python_asset"] # This metadata specifies the corresponding Dagster asset for this dbt source.
