name: DBT CI/CD UPLOAD_TO_S3

on:
  schedule:
   - cron: '0 0 * * *' # Runs every 5 minutes
  push:
    branches:
      - main
  workflow_dispatch: # To allow for manual trigger

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DBT and Snowflake adapter
        run: |
          pip install dbt-core dbt-snowflake


      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          jaffle_shop:
            outputs:
              dev:
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USERNAME }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                threads: 4
                type: snowflake
            target: dev
          EOF

      - name: DBT debug
        run: dbt debug

      - name: DBT deps
        run: dbt deps

      - name: DBT compile  # Optional but recommended
        run: dbt compile

      - name: DBT test
        run: dbt test

  dbt_cd:
    runs-on: ubuntu-latest
    needs: dbt_ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DBT and Snowflake adapter
        run: |
          pip install dbt-core dbt-snowflake

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          jaffle_shop:
            outputs:
              dev:
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USERNAME }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                threads: 4  # Changed from 16 to match CI
                type: snowflake
            target: dev
          EOF

      - name: DBT deps
        run: dbt deps

      - name: DBT run staging
        run: dbt run -s tag:staging

      - name: DBT run intermediate
        run: dbt run -s tag:intermediate

      - name: DBT run marts
        run: dbt run -s tag:marts

  upload_to_s3:
    runs-on: ubuntu-latest
    needs: dbt_cd
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Upload files to S3 (Private)
        run: |
          aws s3 sync . s3://dbt-project --exclude ".git/*"
